version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    restart: always
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST}       # From Render's PostgreSQL add-on
      - GITEA__database__NAME=${POSTGRES_DATABASE}    # From Render's PostgreSQL add-on
      - GITEA__database__USER=${POSTGRES_USER}        # From Render's PostgreSQL add-on
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}  # From Render's PostgreSQL add-on
      - GITEA__server__ROOT_URL=https://${RENDER_SERVICE_NAME}.onrender.com
      - GITEA__server__SSH_PORT=2222                 # Use non-privileged port for SSH
    ports:
      - "3000:3000"
      - "2222:2222"    # Map Render's public port to Gitea's SSH port
    volumes:
      - gitea_data:/data

volumes:
  gitea_data: