version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: gitea
    volumes:
      - mysql_data:/var/lib/mysql

  gitea:
    image: gitea/gitea:latest
    restart: always
    depends_on:
      - mysql
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    ports:
      - "3000:3000"
      - "22:22"
    volumes:
      - gitea_data:/data

volumes:
  mysql_data:
  gitea_data:
